language: node_js
node_js:
  - "12"
jobs:
  include:
    - stage: build
      script: grunt travis
cache:
  npm: false
notifications:
  email:
    recipients: 
    - helpfulscripts@gmail.com
    on_success: never # default: change
    on_failure: always # default: always